//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateDoctorsApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public string Education { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
